### ISSUE TITLE
AppDynamics reports errors for 404s for known behavior

### ISSUE THREAD

**Issue by jconnolly** [bazaarvoice/seo_sdk_java#12]
Hello, we're using appdynamics and bazaarvoice at my organization. I happened to notice the huge numbers of errors reported by appdynamics because this line is failing on products with no reviews:

https://github.com/bazaarvoice/seo_sdk_java/blob/218d8a1606f76fd89b0013351465047f64cc1b76/src/main/java/com/bazaarvoice/seo/sdk/BVUIContentServiceProvider.java#L211

java.io.FileNotFoundException
http://seo.bazaarvoice.com/perfumania-47c02ed0cca1c657e83a0d7544d7a0d2/Main_Site-en_US/reviews/product/1/110000321.htm
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1479)
at com.bazaarvoice.seo.sdk.BVUIContentServiceProvider.loadContentFromHttp(BVUIContentServiceProvider.java:211)
at com.bazaarvoice.seo.sdk.BVUIContentServiceProvider.getBvContent(BVUIContentServiceProvider.java:145)
at com.bazaarvoice.seo.sdk.BVUIContentServiceProvider.call(BVUIContentServiceProvider.java:85)
at com.bazaarvoice.seo.sdk.BVUIContentServiceProvider.call(BVUIContentServiceProvider.java:57)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
at java.util.concurrent.FutureTask.run(FutureTask.java:149)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
at java.lang.Thread.run(Thread.java:767) 

Might want to catch that, since this is definitely a known behavior and not an exceptional behavior.

Thanks.

**Comment by alanlapthorn-bv** [comment]
Archiving repo
