### ISSUE TITLE
BVHTMLFooter is depending on log4j

### ISSUE THREAD

**Issue by jv828642** [bazaarvoice/seo_sdk_java#9]
The pom states that log4j is in scope test bug the BVHTMLFooter velocity template is Log4JLogChute and so requiring log4j.  We had a lot of debug errors, our logs where over floating with the debug error:

 [debug] Couldn't find class org.apache.velocity.runtime.log.Log4JLogChute or necessary supporting classes in classpath.
org/apache/log4j/Layout
java.lang.NoClassDefFoundError: org/apache/log4j/Layout
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.velocity.util.ClassUtils.getClass(ClassUtils.java:63)
	at org.apache.velocity.util.ClassUtils.getNewInstance(ClassUtils.java:95)
	at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:147)
	at org.apache.velocity.runtime.log.LogManager.updateLog(LogManager.java:208)
	at org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:728)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:240)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1099)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1077)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:528)
	at com.bazaarvoice.seo.sdk.footer.BVHTMLFooter.displayFooter(BVHTMLFooter.java:92)

Because we don't have log4j on our classpath, we are using logback as the log framework, the sdk however depends on slf4j so why log4j is in the footer I don't know.

Kind regards,

Joris Vanleene.

**Comment by jv828642** [comment]
Should use org.apache.velocity.slf4j.Slf4jLogChute()

**Comment by jv828642** [comment]
Eventually when it can't find log4j the SystemLogChute is use and prints out System.err.print and printStackTrace thats why are log files are full of it.

**Comment by Priyanka2506** [comment]
@jv828642 which version of velocity jar has slf4j ?

**Comment by alanlapthorn-bv** [comment]
Archiving repo
